-- Create database for ride service performance analysis
CREATE DATABASE RIDE_ANALYSIS;

-- Select the database to work with
USE RIDE_ANALYSIS;

-- Create table to store hourly ride and earnings data for Namma and Taxi
CREATE TABLE RIDE_COMPARISON (
DATE DATE,
HOUR INT,
COMPLETED_RIDES_NAMMA INT,
TOTAL_EARNING_NAMMA FLOAT,
COMPLETED_RIDES_TAXI INT,
TOTAL_EARNING_TAXI FLOAT
);

-- Preview first 10 rows of the dataset
SELECT * FROM RIDE_COMPARISON LIMIT 10;

-- Display the entire dataset
SELECT * FROM RIDE_COMPARISON;

-- Count total number of records in the dataset
SELECT COUNT(*) FROM RIDE_COMPARISON;

-- View table structure and column details
DESCRIBE RIDE_COMPARISON;

-- Identify the hour with the highest total ride demand
SELECT HOUR, SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES
FROM RIDE_COMPARISON
GROUP BY HOUR 
ORDER BY TOTAL_RIDES DESC 
LIMIT 1;

-- Find the date with the highest combined earnings
SELECT DATE, ROUND(SUM(TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI), 2) AS TOTAL_EARNING
FROM RIDE_COMPARISON
GROUP BY DATE
ORDER BY TOTAL_EARNING DESC
LIMIT 1;

-- Top 5 hours with highest earnings for Namma
SELECT HOUR, SUM(TOTAL_EARNING_NAMMA) AS NAMMA_EARNINGS
FROM RIDE_COMPARISON
GROUP BY HOUR 
ORDER BY NAMMA_EARNINGS DESC
LIMIT 5;

-- Top 5 hours with lowest earnings for Taxi
SELECT HOUR, ROUND(SUM(TOTAL_EARNING_TAXI), 2) AS TAXI_EARNINGS
FROM RIDE_COMPARISON
GROUP BY HOUR
ORDER BY TAXI_EARNINGS
LIMIT 5;

-- Total rides completed by Namma vs Taxi
SELECT SUM(COMPLETED_RIDES_NAMMA) AS TOTAL_NAMMA_RIDES, SUM(COMPLETED_RIDES_TAXI) AS TOTAL_TAXI_RIDES
FROM RIDE_COMPARISON;

-- Total earnings comparison between Namma and Taxi
SELECT SUM(TOTAL_EARNING_NAMMA) AS TOTAL_NAMMA_EARNINGS, ROUND(SUM(TOTAL_EARNING_TAXI), 2) AS TOTAL_TAXI_EARNINGS
FROM RIDE_COMPARISON;

-- Identify hours where Taxi rides exceeded Namma rides
SELECT DATE, HOUR, COMPLETED_RIDES_NAMMA, COMPLETED_RIDES_TAXI
FROM RIDE_COMPARISON
WHERE COMPLETED_RIDES_TAXI > COMPLETED_RIDES_NAMMA;

-- Calculate average earnings per ride for Namma
SELECT ROUND(SUM(TOTAL_EARNING_NAMMA) / SUM(COMPLETED_RIDES_NAMMA), 2) AS AVG_EARNING_PER_RIDE
FROM RIDE_COMPARISON; 

-- Calculate average earnings per ride for Taxi
SELECT ROUND(SUM(TOTAL_EARNING_TAXI) / SUM(COMPLETED_RIDES_TAXI), 2) AS AVG_EARNING_PER_RIDE
FROM RIDE_COMPARISON;

-- Identify dates with the highest ride demand
SELECT DATE, SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES
FROM RIDE_COMPARISON
GROUP BY DATE
ORDER BY TOTAL_RIDES DESC;

-- Compare daily earnings difference between Namma and Taxi
SELECT DATE, ROUND(SUM(TOTAL_EARNING_NAMMA) - SUM(TOTAL_EARNING_TAXI), 2) AS EARNING_DIFFERENCE
FROM RIDE_COMPARISON
GROUP BY DATE;

-- Highest hourly ride count for Namma
SELECT DATE, HOUR, SUM(COMPLETED_RIDES_NAMMA) AS TOTAL_RIDES 
FROM RIDE_COMPARISON
GROUP BY DATE, HOUR
ORDER BY TOTAL_RIDES DESC; 

-- Highest hourly ride count for Taxi
SELECT DATE, HOUR, SUM(COMPLETED_RIDES_TAXI) AS TOTAL_RIDES
FROM RIDE_COMPARISON
GROUP BY DATE, HOUR 
ORDER BY TOTAL_RIDES DESC;

-- Identify individual time slots with the highest combined ride demand
SELECT DATE, HOUR, (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES
FROM RIDE_COMPARISON
ORDER BY TOTAL_RIDES DESC;

-- Rank hours based on total ride demand using window functions
SELECT HOUR, SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES,
RANK() OVER(ORDER BY SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) DESC) AS RIDE_RANK
FROM RIDE_COMPARISON
GROUP BY HOUR;

-- Identify hours where total earnings exceeded 5000
SELECT DATE, HOUR, ROUND(TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI, 2) AS TOTAL_EARNINGS
FROM RIDE_COMPARISON 
WHERE TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI > 5000;

-- Calculate percentage share of rides completed by Namma
SELECT ROUND((SUM(COMPLETED_RIDES_NAMMA) * 100.0) / SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI), 2) AS NAMMA_PERCENTAGES
FROM RIDE_COMPARISON;

-- Calculate percentage share of rides completed by Taxi
SELECT ROUND((SUM(COMPLETED_RIDES_TAXI) * 100.0) / SUM(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI), 2) AS TAXI_PERCENTAGES
FROM RIDE_COMPARISON;

-- Identify time slots with the largest earnings gap between services
SELECT DATE, HOUR, ROUND((TOTAL_EARNING_NAMMA - TOTAL_EARNING_TAXI), 2) AS EARNING_GAP
FROM RIDE_COMPARISON
ORDER BY EARNING_GAP DESC
LIMIT 5;

-- Compare ride demand with the previous hour using LAG function
SELECT DATE, HOUR, (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES, 
LAG(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) OVER(ORDER BY DATE, HOUR) AS PREVIOUS_HOUR_RIDES
FROM RIDE_COMPARISON;

-- Identify the longest consecutive streak where Namma had more completed rides than Taxi
WITH BASE AS (SELECT DATE, HOUR, CASE WHEN COMPLETED_RIDES_NAMMA > COMPLETED_RIDES_TAXI THEN 1 ELSE 0 END AS NAMMA_WIN
FROM RIDE_COMPARISON
ORDER BY DATE, HOUR),
ORDERED AS (SELECT *, ROW_NUMBER() OVER(ORDER BY DATE, HOUR) AS RN
FROM BASE),
CONSECUTIVE_GROUPS AS (SELECT *, RN - ROW_NUMBER() OVER(PARTITION BY NAMMA_WIN ORDER BY DATE, HOUR) AS GRP
FROM ORDERED)
SELECT MIN(DATE) AS START_DATE, MIN(HOUR) AS START_HOUR, MAX(DATE) AS END_DATE,MAX(HOUR) AS START_HOUR, COUNT(*) AS STREAK_LENGTH
FROM CONSECUTIVE_GROUPS
WHERE NAMMA_WIN = 1
GROUP BY GRP
ORDER BY STREAK_LENGTH DESC;

-- Detect periods where Taxi earnings increased continuously for four consecutive time slots
WITH EARNINGS_LAG AS (SELECT DATE, HOUR, TOTAL_EARNING_TAXI, LAG(TOTAL_EARNING_TAXI, 1) OVER(ORDER BY DATE, HOUR) AS PREV1,
LAG(TOTAL_EARNING_TAXI, 2) OVER(ORDER BY DATE, HOUR) AS PREV2,
LAG(TOTAL_EARNING_TAXI, 3) OVER(ORDER BY DATE, HOUR) AS PREV3
FROM RIDE_COMPARISON)
SELECT DATE, HOUR, TOTAL_EARNING_TAXI
FROM EARNINGS_LAG
WHERE PREV3 < PREV2
AND PREV2 < PREV1
AND PREV1 < TOTAL_EARNING_TAXI;

-- Identify sudden spikes in ride demand where rides increased by more than 50% compared to the previous hour
WITH RIDES AS (SELECT DATE, HOUR, (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) AS TOTAL_RIDES,
LAG(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI) OVER(ORDER BY DATE, HOUR) AS PREV_RIDES
FROM RIDE_COMPARISON)
SELECT * 
FROM RIDES
WHERE (TOTAL_RIDES - PREV_RIDES) / PREV_RIDES > 0.5;

-- Find the time slot where Namma had the highest ride share compared to Taxi
WITH SHARE_CALC AS (SELECT DATE, HOUR, COMPLETED_RIDES_NAMMA, COMPLETED_RIDES_TAXI, 
(COMPLETED_RIDES_NAMMA / (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI)) AS NAMMA_SHARE
FROM RIDE_COMPARISON)
SELECT * FROM SHARE_CALC ORDER BY NAMMA_SHARE DESC LIMIT 1;

-- Identify the top 3 highest earning hours for each day
WITH EARNINGS_RANK AS (SELECT DATE, HOUR, ROUND((TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI), 2) AS TOTAL_EARNINGS,
ROW_NUMBER() OVER(PARTITION BY DATE ORDER BY (TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI) DESC) AS RNK
FROM RIDE_COMPARISON)
SELECT * FROM EARNINGS_RANK WHERE RNK <= 3;

-- Detect abnormal earnings spikes where hourly earnings are more than twice the daily average
SELECT DATE, HOUR, ROUND((TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI), 2) AS TOTAL_EARNINGS
FROM RIDE_COMPARISON R 
WHERE (TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI) > 2 * (SELECT AVG(TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI) FROM RIDE_COMPARISON WHERE DATE = R.DATE);

-- Compare earnings efficiency (earnings per ride) between Namma and Taxi and rank Namma performance
SELECT DATE, HOUR, ROUND(TOTAL_EARNING_NAMMA / COMPLETED_RIDES_NAMMA, 2) AS NAMMA_EFFICIENCY,
ROUND(TOTAL_EARNING_TAXI / COMPLETED_RIDES_TAXI, 2) AS TAXI_EFFICIENCY,
RANK() OVER(ORDER BY TOTAL_EARNING_NAMMA / COMPLETED_RIDES_NAMMA DESC) NAMMA_RANK
FROM RIDE_COMPARISON;

-- Calculate the growth rate of Namma earnings compared to the previous hour
SELECT DATE, HOUR, TOTAL_EARNING_NAMMA, LAG(TOTAL_EARNING_NAMMA) OVER(ORDER BY DATE, HOUR) AS PREV_EARNING, 
ROUND(((TOTAL_EARNING_NAMMA - LAG(TOTAL_EARNING_NAMMA) OVER(ORDER BY DATE, HOUR)) / LAG(TOTAL_EARNING_NAMMA) OVER(ORDER BY DATE, HOUR)) * 100, 2) AS GROWTH_RATE
FROM RIDE_COMPARISON;

-- Calculate daily market share of Namma based on total earnings
SELECT DATE, SUM(TOTAL_EARNING_NAMMA) / SUM(TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI) AS NAMMA_SHARE
FROM RIDE_COMPARISON
GROUP BY DATE
ORDER BY NAMMA_SHARE DESC;

-- Identify time points where service dominance switched from Namma to Taxi
WITH WINS AS (SELECT DATE, HOUR, CASE WHEN COMPLETED_RIDES_NAMMA > COMPLETED_RIDES_TAXI THEN 'NAMMA' ELSE 'TAXI' END AS WINNER
FROM RIDE_COMPARISON)
SELECT DATE, HOUR, WINNER FROM (SELECT *, LAG(WINNER) OVER(ORDER BY DATE, HOUR) AS PREV_WINNER
FROM WINS) T
WHERE PREV_WINNER = 'NAMMA'
AND WINNER = 'TAXI';

-- Identify the top 3 peak hours based on average ride demand
SELECT HOUR, ROUND(AVG(COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI), 2) AS AVG_RIDES
FROM RIDE_COMPARISON
GROUP BY HOUR 
ORDER BY AVG_RIDES DESC
LIMIT 3;

-- Detect periods where the earnings gap between Namma and Taxi is increasing
WITH GAP_CALC AS (SELECT DATE, HOUR, ROUND((TOTAL_EARNING_NAMMA - TOTAL_EARNING_TAXI), 2) AS GAP,
ROUND(LAG(TOTAL_EARNING_NAMMA - TOTAL_EARNING_TAXI) OVER(ORDER BY DATE, HOUR), 2) AS PREV_GAP
FROM RIDE_COMPARISON)
SELECT * FROM GAP_CALC WHERE GAP > PREV_GAP;

-- Measure daily volatility in Namma ride share compared to Taxi using standard deviation
SELECT DATE, ROUND(STDDEV(COMPLETED_RIDES_NAMMA / (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI)), 2) AS VOLATILITY
FROM RIDE_COMPARISON
GROUP BY DATE 
ORDER BY VOLATILITY DESC;

-- Calculate a dominance score combining ride share and earnings share for Namma
WITH DOMINANCE AS (SELECT DATE, HOUR, (COMPLETED_RIDES_NAMMA / (COMPLETED_RIDES_NAMMA + COMPLETED_RIDES_TAXI)) AS RIDE_SHARE,
(TOTAL_EARNING_NAMMA / (TOTAL_EARNING_NAMMA + TOTAL_EARNING_TAXI)) AS EARNING_SHARE
FROM RIDE_COMPARISON)
SELECT DATE, HOUR, ROUND((RIDE_SHARE + EARNING_SHARE), 2) / 2 AS DOMINANCE_SCORE
FROM DOMINANCE
ORDER BY DOMINANCE_SCORE DESC 
LIMIT 10;
